version: '3.8'
services:
 sqlserver:
   image: mcr.microsoft.com/mssql/server:2019-latest
   environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=Sql123Server
   ports:
     - "1433:1433"
   volumes:
     - sqlserver_data:/var/opt/mssql
   restart: always
   healthcheck:
     test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Sql123Server -Q 'SELECT 1' || exit 1"]
     interval: 10s
     retries: 10
     start_period: 10s
     timeout: 3s
   networks:
     - mynetwork
volumes:
 sqlserver_data:
networks:
 mynetwork:
   driver: bridge